name: Build and Deploy

on:
  workflow_run:
    workflows:
      - Test App
    types:
      - completed
    branches:
      main

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    env:
      DOCKER_IMAGE_NAME: ${{ vars.GCLOUD_REGION }}-docker.pkg.dev/${{ vars.GCLOUD_PROJECT_ID }}/${{ vars.GCLOUD_REPO }}/${{ vars.GCLOUD_SERVICE_NAME }}:${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCLOUD_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # Helpful for debugging
      # - name: Display Google Cloud environment information
      #   run: gcloud info

      # Or use docker/login-action@v3, see https://cloud.google.com/blog/products/devops-sre/deploy-to-cloud-run-with-github-actions
      - name: Authenticate Docker to Artifact Registry
        run: |
          gcloud auth configure-docker ${{ vars.GCLOUD_REGION }}-docker.pkg.dev --quiet

      # Or use docker/build-push-action@v3, see https://cloud.google.com/blog/products/devops-sre/deploy-to-cloud-run-with-github-actions
      - name: Build image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_NAME }} .

      - name: Push image
        run: |
          docker push ${{ env.DOCKER_IMAGE_NAME }}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ vars.GCLOUD_SERVICE_NAME }}
          region: ${{ vars.GCLOUD_REGION }}
          image: ${{ env.DOCKER_IMAGE_NAME }}
          env_vars: |
           NODE_ENV=production

      - name: Log app URL
        run: echo ${{ steps.deploy.outputs.url }}
