name: Build and Push to Artifact Registry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGION: us-east4
  GAR_LOCATION: us-east4-docker.pkg.dev/mandelbrot-explorer-403805/repo1/mandelbrot-explorer-app

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCLOUD_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # Helpful for debugging
      # - name: Display Google Cloud environment information
      #   run: gcloud info

      - name: Configure Docker authentication to Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build image
        run: docker build -t ${{ env.GAR_LOCATION }}:${{ github.sha }} .

      - name: Push image
        run: docker push ${{ env.GAR_LOCATION }}:${{ github.sha }}
